### ISSUE TITLE
Enable support for MKS Wifi module

### ISSUE THREAD

**Issue by wolllis** [NARUTOfzr/Neptune_3#2]
Hello @NARUTOfzr,

It would be nice to have this feature active like in the Neptune 2 printer :)

I noticed the support for MKS Wifi module being disabled in the project configuration.
Is there any particular software/hardware related reason for this? If its just not tested then I may support here.

Best regards,
wolllis

**Comment by NARUTOfzr** [comment]
The hardware of this motherboard supports the extension of MKs_wifi module. However, current firmware does not support this feature.

**Comment by NARUTOfzr** [comment]
> Hello @NARUTOfzr,
> 
> It would be nice to have this feature active like in the Neptune 2 printer :)
> 
> I noticed the support for MKS Wifi module being disabled in the project configuration. Is there any particular software/hardware related reason for this? If its just not tested then I may support here.
> 
> Best regards, wolllis

The hardware of this motherboard supports the extension of MKs_wifi module. However, current firmware does not support this feature.

**Comment by wolllis** [comment]
Thanks for clarification. Hope it will be added somewhere in the future,
Cheers
