### ISSUE TITLE
 purchase of spare parts

### ISSUE THREAD

**Issue by Qubicone** [NARUTOfzr/Neptune_3#36]
hello, 
my hotend is bent because the sensor for the z offset / autolevel no longer works.
so i can't use the printer at the moment.
Please tell me where I can buy these parts.

KR
Qubicone

**Comment by NARUTOfzr** [comment]
@Qubicone Hi! Please send a photo of your order number and the damaged part to elegoo support email: 3dp@elegoo.com. They'll take care of it for you.

**Comment by NARUTOfzr** [comment]
Perhaps you could describe the situation. Take video feedback. I'll see if there's anything else I can do.

**Comment by Qubicone** [comment]
der Elegoo Support hat mir sehr rasch und kompetent geholfen.

**Comment by Qubicone** [comment]
Elegoo Support helped me very quickly and competently.
